In [59]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [5]:
arr=np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mymatrix.shape


(3, 3)

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.0)

float

In [18]:
type(0.)

float

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
np.ones(4)* 100

array([100., 100., 100., 100.])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
len(np.linspace(0,10,20))

20

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#Numpy Array Part Two:

In [30]:
np.random.rand(1)

array([0.4385732])

In [31]:
np.random.rand(4)

array([0.51357283, 0.32572426, 0.39303442, 0.63372884])

In [32]:
np.random.rand(5,5)

array([[0.72621256, 0.58566351, 0.11534847, 0.58868727, 0.82010184],
       [0.3941702 , 0.69505428, 0.78089818, 0.05502469, 0.86684142],
       [0.97433699, 0.94056782, 0.57031658, 0.58229749, 0.28549509],
       [0.23677616, 0.95177559, 0.6046093 , 0.40220485, 0.45314427],
       [0.44243945, 0.80202347, 0.00517479, 0.0583318 , 0.05566388]])

In [33]:
np.random.randn(10)

array([ 1.5377062 ,  0.06633582,  1.07824401,  1.54319637,  0.85335969,
       -0.7557657 ,  0.64206388, -0.7112983 ,  0.88048749, -0.67335894])

In [35]:
# np.random.normal

In [39]:
np.random.randint(1,100,10)

array([27, 46, 60, 92,  6, 11, 63, 98, 95, 28])

In [65]:
np.random.seed(42)
np.random.rand(4)
# if you are getting same random number then
# seed and rand are in same shell 
#in seed you can pass any number

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [67]:
arr=np.arange(25)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
ranarr=np.random.randint(0,50,10)

In [77]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [72]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
ranarr.max()

43

In [79]:
ranarr.min()

1

In [81]:
ranarr.argmax()

3

In [82]:
ranarr.argmin()

1

In [83]:
ranarr.dtype

dtype('int32')

In [84]:
# numpy indexing and selection

In [85]:
import numpy as np

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[8]

8

In [89]:
arr[1:5]

array([1, 2, 3, 4])

In [90]:
arr[:5]

array([0, 1, 2, 3, 4])

In [91]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [98]:
new_arr=arr / 2

In [99]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [ ]:
#broadcasting

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
slice_of_arr=arr[0:6]

In [104]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [107]:
slice_of_arr[:]=99

In [108]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [109]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [110]:
arr_copy=arr.copy()

In [111]:
arr_copy[:]=10000

In [112]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [113]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [114]:
#indexing in @d array

In [115]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [116]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [117]:
arr_2d.shape

(3, 3)

In [118]:
arr_2d[1]

array([20, 25, 30])

In [119]:
arr_2d[1][1]

25

In [120]:
arr_2d[1,1]

25

In [121]:
arr=np.arange(1,11)

In [122]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [124]:
bool_arr =arr >4

In [125]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [126]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [127]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [128]:
arr[arr <=6]

array([1, 2, 3, 4, 5, 6])

In [129]:
arr[arr ==2]

array([2])

In [130]:
#4 NUMpy Operation

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [7]:
arr /100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [8]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
(arr +2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
1/arr

C:\Users\SHRI\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
arr/arr

C:\Users\SHRI\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.log(arr)

C:\Users\SHRI\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
arr.sum()

45

In [23]:
arr.mean()

4.5

In [24]:
arr.max()

9

In [25]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [26]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr_2d.shape

(3, 4)

In [28]:
arr_2d.sum()

78

In [29]:
# give me sum across the rows
arr_2d.sum(axis=0)
#sum of all values in the colums

array([15, 18, 21, 24])

In [30]:
# give me sum across the colums
arr_2d.sum(axis=1)
#sum of all values in the colums

array([10, 26, 42])